# Generated by Django 2.2.6 on 2019-10-27 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='device',
            field=models.ManyToManyField(to='database.Device'),
        ),
        migrations.DeleteModel(
            name='Monitors',
        ),
    ]
