# Generated by Django 2.2.6 on 2019-10-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191023_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitors',
        ),
    ]
