# Generated by Django 2.2.6 on 2019-11-03 13:59

import database.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20191027_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='som',
            new_name='sound',
        ),
        migrations.RemoveField(
            model_name='device',
            name='potency',
        ),
        migrations.AddField(
            model_name='potency',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Device'),
        ),
        migrations.AlterField(
            model_name='potency',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 13, 59, 52, 794419, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), database.models.max_value_current_year])),
                ('potency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Potency')),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(default=1)),
                ('potency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Potency')),
            ],
        ),
    ]
