# Generated by Django 2.2.6 on 2019-11-03 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20191103_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='potency',
        ),
        migrations.RemoveField(
            model_name='year',
            name='potency',
        ),
        migrations.AddField(
            model_name='potency',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Month'),
        ),
        migrations.AddField(
            model_name='potency',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.Year'),
        ),
        migrations.AlterField(
            model_name='potency',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 14, 24, 13, 27614, tzinfo=utc)),
        ),
    ]
