# Generated by Django 2.2.6 on 2019-11-03 16:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20191103_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potency',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 16, 39, 36, 509681, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='potency',
            name='month',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='database.Month'),
        ),
        migrations.AlterField(
            model_name='potency',
            name='year',
            field=models.ForeignKey(default=2019, on_delete=django.db.models.deletion.CASCADE, to='database.Year'),
        ),
    ]
