# Generated by Django 2.2.6 on 2019-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20191103_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='potency',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
