# Generated by Django 2.2.6 on 2019-11-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20191106_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
