# Generated by Django 2.2.6 on 2019-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20191110_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
