# Generated by Django 2.2.6 on 2019-11-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20191112_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=100),
        ),
    ]
